version: "3.8"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: planitly
      POSTGRES_PASSWORD: planitly
      POSTGRES_USER: planitly
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - ./docker/postgres:/var/lib/postgres
volumes:
  postgres:
    driver: local