name: develop workflow

on:
  push:
    branches: [develop]

jobs:
  docker-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build
        run: docker build . -t octavianregatun/planitly-backend-nestjs:develop

      - name: Docker push
        run: docker push octavianregatun/planitly-backend-nestjs:develop